import * as yup from 'yup';

export const ITEquipmentSchema = yup.object().shape({
    assetName: yup.string().required('Name is required'),
    hostname: yup.string().required('Name is required'),
    detailNetBookValue: yup.string().required('Name is required'),
    engravedNumber: yup.string().required('Name is required'),
    dateReceipt: yup.string().required('Name is required'),
    make: yup.string().required('Name is required'),
    assetCategory_id: yup.string().required('Name is required'),
    supplier: yup.string().required('Name is required'),
    unitOfMeasure: yup.string().required('Name is required'),
    purchaseCost: yup.string().required('Name is required'),
    costOfTheAsset: yup.string().required('Name is required'),
    netValueB: yup.string().required('Name is required'),
    model: yup.string().nullable().optional(),
    serialNumber: yup.string().nullable().optional(),
    user_id: yup.string().nullable().optional(),
    ram: yup.string().nullable().optional(),
    cpuSpeed: yup.string().nullable().optional(),
    hardDiskSize: yup.string().nullable().optional(),
    location: yup.string().nullable().optional(),
    macAddress: yup.string().nullable().optional(),
    ipAddress: yup.string().nullable().optional(),
    interfaceType: yup.string().nullable().optional(),
    assetDepreciationRate: yup.string().nullable().optional(),
    assetSubCategory_id: yup.string().nullable().optional(),
    desc: yup.string().nullable().optional(),
    image: yup.string().nullable().optional(),
    assetStatus: yup.string().nullable().optional(),
    category: yup.string().nullable().optional(),
});
