/*
13.9 Pride's Standard Copyright Notice:
Copyright ©20XX. Management of Pride Bank Limited (PBL). All Rights Reserved. Permission to use, copy, modify, 
and distribute this software and its documentation for any purpose is prohibited unless authorized in writing by the
Managing Director
*/

import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

export const exportExcel = async (columns, rows, fileName) => {
    try {
        // Create a new workbook with two worksheets: cover page and data
        const workbook = new ExcelJS.Workbook();

        // WORKSHEET 1: COVER PAGE
        const coverSheet = workbook.addWorksheet('Cover', {
            pageSetup: {
                orientation: 'portrait',
                fitToPage: true
            },
            properties: { tabColor: { argb: 'FF087970' } }
        });

        // WORKSHEET 2: DATA PAGE
        const dataSheet = workbook.addWorksheet('Data', {
            pageSetup: {
                orientation: 'landscape',
                fitToPage: true
            },
            properties: { tabColor: { argb: 'FF4B88A2' } }
        });

        // Set print area for data sheet
        dataSheet.pageSetup.printArea = 'A1:Z1000';

        // Define brand colors
        const primaryColor = { argb: 'FF087970' }; // RGB 8, 121, 108
        const secondaryColor = { argb: 'FF4B88A2' }; // Secondary accent color
        const headerFontColor = { argb: 'FFFFFFFF' }; // White
        const borderColor = { argb: 'FFD9D9D9' }; // Light gray
        const highlightColor = { argb: 'FFEEF8F8' }; // Very light teal

        // ===== COVER PAGE DESIGN =====

        // Set column widths for cover page
        coverSheet.columns = [
            { width: 5 },  // A - left margin
            { width: 30 }, // B - content 
            { width: 25 }, // C - content
            { width: 25 }, // D - content
            { width: 5 }   // E - right margin
        ];

        // Add spacing at top
        coverSheet.addRow([]);
        coverSheet.addRow([]);
        coverSheet.addRow([]);

        // Add report title
        const titleRow = coverSheet.addRow(['', `${fileName.charAt(0).toUpperCase() + fileName.slice(1)} Report`, '', '']);
        titleRow.height = 50;
        coverSheet.mergeCells('B4:D4');
        const titleCell = coverSheet.getCell('B4');
        titleCell.font = { bold: true, size: 28, color: primaryColor };
        titleCell.alignment = { horizontal: 'center' };

        coverSheet.addRow([]);

        // Add horizontal separator
        const separatorRow = coverSheet.addRow(['', '', '', '']);
        separatorRow.height = 3;
        coverSheet.mergeCells('B6:D6');
        const separatorCell = coverSheet.getCell('B6');
        separatorCell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: primaryColor
        };

        coverSheet.addRow([]);
        coverSheet.addRow([]);

        // Add report information in a cleaner layout using grid
        const today = new Date();
        const formattedDate = today.toLocaleDateString('en-US', {
            year: 'numeric', month: 'long', day: 'numeric'
        });
        const formattedTime = today.toLocaleTimeString('en-US', {
            hour: '2-digit', minute: '2-digit'
        });

        // Add information section with a border box
        const infoStartRow = 9;
        coverSheet.addRow(['', 'REPORT DETAILS', '', '']);
        coverSheet.getCell('B9').font = { bold: true, size: 14 };
        coverSheet.addRow(['', 'Date Generated:', formattedDate, '']);
        coverSheet.addRow(['', 'Time Generated:', formattedTime, '']);
        coverSheet.addRow(['', 'Total Records:', rows.length.toString(), '']);
        coverSheet.addRow(['', 'Generated By:', 'Pride Asset Management System', '']);
        coverSheet.addRow(['']);

        // Style the info box with a border
        ['B', 'C', 'D'].forEach(col => {
            coverSheet.getCell(`${col}9`).fill = {
                type: 'pattern', pattern: 'solid', fgColor: secondaryColor
            };
            coverSheet.getCell(`${col}9`).font = { bold: true, color: headerFontColor };
        });

        // Add borders around info box
        for (let r = infoStartRow; r < infoStartRow + 5; r++) {
            ['B', 'C', 'D'].forEach(col => {
                const cell = coverSheet.getCell(`${col}${r}`);
                cell.border = {
                    top: { style: r === infoStartRow ? 'medium' : 'thin', color: borderColor },
                    left: { style: col === 'B' ? 'medium' : 'thin', color: borderColor },
                    bottom: { style: r === infoStartRow + 4 ? 'medium' : 'thin', color: borderColor },
                    right: { style: col === 'D' ? 'medium' : 'thin', color: borderColor }
                };

                // Alternate row coloring
                if ((r - infoStartRow) % 2 === 1) {
                    cell.fill = {
                        type: 'pattern',
                        pattern: 'solid',
                        fgColor: highlightColor
                    };
                }
            });
        }

        // Add a company signature section
        coverSheet.addRow([]);
        coverSheet.addRow([]);
        coverSheet.addRow(['', 'Pride Bank Limited', '', '']);
        coverSheet.getCell('B16').font = { bold: true, size: 18, color: primaryColor };
        coverSheet.addRow(['', 'Asset Management System', '', '']);
        coverSheet.getCell('B17').font = { italic: true, size: 14, color: secondaryColor };

        // Add confidential watermark diagonally
        coverSheet.addRow([]);
        coverSheet.addRow([]);
        coverSheet.addRow(['', 'CONFIDENTIAL', '', '']);
        coverSheet.mergeCells('B20:D20');
        const watermarkCell = coverSheet.getCell('B20');
        watermarkCell.font = { bold: true, color: { argb: '15087970' }, size: 72 };
        watermarkCell.alignment = { vertical: 'middle', horizontal: 'center', textRotation: 45 };

        // Add footer with company info and copyright
        coverSheet.addRow([]);
        coverSheet.addRow([]);
        coverSheet.addRow([]);
        coverSheet.addRow([]);
        coverSheet.addRow(['', `© ${new Date().getFullYear()} Pride Bank Limited. All rights reserved.`, '', '']);
        coverSheet.mergeCells('B25:D25');
        coverSheet.getCell('B25').font = { italic: true, size: 10, color: { argb: 'FF777777' } };
        coverSheet.getCell('B25').alignment = { horizontal: 'center' };

        // ===== DATA PAGE DESIGN =====

        // Intelligently set column widths based on content and headers
        const dataColumnWidths = columns.map(col => {
            // Calculate the ideal width based on header length
            const baseWidth = Math.max(12, col.title.length * 1.2);

            // Adjust width based on expected content type
            const key = col.dataKey.toLowerCase();

            if (key.includes('name') || key.includes('description')) {
                return { header: col.title, key: col.dataKey, width: Math.max(baseWidth, 25) };
            } else if (key.includes('date')) {
                return { header: col.title, key: col.dataKey, width: 15 };
            } else if (key.includes('status')) {
                return { header: col.title, key: col.dataKey, width: 12 };
            } else if (key.includes('email')) {
                return { header: col.title, key: col.dataKey, width: 25 };
            } else if (key.includes('number') || key.includes('phone')) {
                return { header: col.title, key: col.dataKey, width: 15 };
            } else if (key.includes('cost') || key.includes('price') || key.includes('amount')) {
                return { header: col.title, key: col.dataKey, width: 15 };
            } else {
                return { header: col.title, key: col.dataKey, width: baseWidth };
            }
        });
        dataSheet.columns = dataColumnWidths;

        // Add report title and metadata to data sheet
        dataSheet.addRow([]).height = 10; // Top margin
        const dataTitle = dataSheet.addRow([`${fileName.charAt(0).toUpperCase() + fileName.slice(1)} Data`]);
        dataTitle.height = 24;
        dataTitle.getCell(1).font = { bold: true, size: 14 };
        dataSheet.addRow([`Generated: ${formattedDate} | Records: ${rows.length}`]);
        dataSheet.getCell('A3').font = { italic: true, size: 10, color: { argb: 'FF666666' } };
        dataSheet.addRow([]).height = 5; // Spacing

        // Create styled table header
        const headerRow = dataSheet.addRow(columns.map(col => col.title));

        // Style header cells
        headerRow.eachCell((cell) => {
            cell.fill = {
                type: 'pattern',
                pattern: 'solid',
                fgColor: primaryColor
            };
            cell.font = { bold: true, color: headerFontColor, size: 11 };
            cell.alignment = { vertical: 'middle', horizontal: 'center' };
            cell.border = {
                top: { style: 'thin', color: borderColor },
                left: { style: 'thin', color: borderColor },
                bottom: { style: 'thin', color: borderColor },
                right: { style: 'thin', color: borderColor }
            };
        });
        headerRow.height = 22; // Slightly taller header

        // Add a subtle striped pattern to the header
        for (let i = 1; i <= columns.length; i += 2) {
            const cell = headerRow.getCell(i);
            cell.fill = {
                type: 'pattern',
                pattern: 'solid',
                fgColor: secondaryColor
            };
        }

        // Add data rows with improved styling
        rows.forEach((dataRow, rowIndex) => {
            const row = dataSheet.addRow(columns.map(col => {
                const value = dataRow[col.dataKey];

                // Format numbers with commas if they look like currency values
                if (typeof value === 'number' &&
                    (col.dataKey.toLowerCase().includes('cost') ||
                        col.dataKey.toLowerCase().includes('price') ||
                        col.dataKey.toLowerCase().includes('amount'))) {
                    return new Intl.NumberFormat('en-UG', {
                        style: 'decimal',
                        useGrouping: true,
                        minimumFractionDigits: 0,
                        maximumFractionDigits: 0
                    }).format(value);
                }

                return value;
            }));

            // Apply alternating row background (subtle)
            if (rowIndex % 2 === 1) {
                row.eachCell((cell) => {
                    cell.fill = {
                        type: 'pattern',
                        pattern: 'solid',
                        fgColor: { argb: 'FFF8FCFC' } // Very light blue-green tint
                    };
                });
            }

            // Apply borders and alignment to all cells
            row.eachCell((cell, colNumber) => {
                // Thinner, lighter borders for a more modern look
                cell.border = {
                    top: { style: 'hair', color: borderColor },
                    left: { style: 'hair', color: borderColor },
                    bottom: { style: 'hair', color: borderColor },
                    right: { style: 'hair', color: borderColor }
                };

                // Set alignment based on content type
                const columnKey = columns[colNumber - 1].dataKey;

                if (typeof cell.value === 'number' ||
                    columnKey.toLowerCase().includes('cost') ||
                    columnKey.toLowerCase().includes('price') ||
                    columnKey.toLowerCase().includes('amount')) {
                    cell.alignment = { horizontal: 'right' };
                    cell.numFmt = '#,##0'; // Number format with thousand separators
                } else if (columnKey.toLowerCase() === 'status') {
                    cell.alignment = { horizontal: 'center' };

                    // Color status cells based on value
                    if (cell.value) {
                        const statusText = cell.value.toString().toLowerCase();

                        if (statusText.includes('active') ||
                            statusText.includes('approved') ||
                            statusText.includes('completed')) {
                            cell.font = { color: { argb: 'FF008000' } }; // Green
                        } else if (statusText.includes('pending')) {
                            cell.font = { color: { argb: 'FFFF9800' } }; // Orange
                        } else if (statusText.includes('reject') ||
                            statusText.includes('cancel') ||
                            statusText.includes('error')) {
                            cell.font = { color: { argb: 'FFD32F2F' } }; // Red
                        }
                    }
                } else if (columnKey.toLowerCase().includes('date')) {
                    cell.alignment = { horizontal: 'center' };
                } else {
                    cell.alignment = { horizontal: 'left' };
                }
            });

            // Set a reasonable row height
            row.height = 18; // Slightly shorter than default for a denser, more modern look
        });

        // Add a thin footer at the bottom of the data
        dataSheet.addRow([]).height = 5;
        const dataFooter = dataSheet.addRow(['Pride Bank Limited - Generated by Asset Management System']);
        dataFooter.getCell(1).font = { italic: true, size: 9, color: { argb: 'FF777777' } };
        dataSheet.mergeCells(`A${dataFooter.number}:${String.fromCharCode(65 + columns.length - 1)}${dataFooter.number}`);

        // Auto-filter and freeze panes for better usability
        dataSheet.autoFilter = {
            from: { row: headerRow.number, column: 1 },
            to: { row: headerRow.number + rows.length, column: columns.length }
        };

        // Freeze the header row when scrolling
        dataSheet.views = [
            { state: 'frozen', xSplit: 0, ySplit: headerRow.number }
        ];

        // Write to file and trigger download
        const buffer = await workbook.xlsx.writeBuffer();
        const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
        saveAs(blob, `${fileName}.xlsx`);
    } catch (error) {
        console.error("Error generating Excel file:", error);
    }
};