/*
13.9 Pride's Standard Copyright Notice:
Copyright ©20XX. Management of Pride Bank Limited (PBL). All Rights Reserved. Permission to use, copy, modify,
and distribute this software and its documentation for any purpose is prohibited unless authorized in writing by the
Managing Director
*/

import jsPDF from 'jspdf';

/**
 * Shared drawing kit for Pride Bank's printable documents (Store Release / Dispatch Note, Goods
 * Received Note).
 *
 * <p>These documents are handed to suppliers and couriers and signed, so they have to look like they
 * came from the same organisation. They were previously generated by unrelated modules — one light
 * and airy in points, the other a boxed, gold-bordered layout in millimetres — which meant a
 * storekeeper could receive two documents for the same delivery that shared no visual language.
 * Holding the palette and the primitives here means a change to one is a change to all of them.
 */

// ── Palette (light, professional) ────────────────────────────────────────────
export const TEAL = '#08796C';
export const TEAL_DARK = '#065E54';
export const TEAL_50 = '#E9F3F1';   // very light brand tint for table heads
export const GOLD = '#BC892C';
export const GOLD_DARK = '#9B7024';
export const INK = '#1E293B';
export const MUTED = '#64748B';
export const FAINT = '#94A3B8';
export const BORDER = '#E5EAF0';
export const WASH = '#F8FAFC';

/** Aspect ratio of pride_logo_horizontal.png (909 × 275). */
export const LOGO_RATIO = 909 / 275;

/**
 * Loads a bundled image URL into a base64 data URL (via canvas) so jsPDF can embed it.
 * Resolves null on any failure so PDF generation never blocks on a missing/broken asset.
 */
export const loadImage = (src: string): Promise<string | null> =>
    new Promise((resolve) => {
        try {
            const img = new Image();
            img.crossOrigin = 'anonymous';
            img.onload = () => {
                try {
                    const canvas = document.createElement('canvas');
                    canvas.width = img.naturalWidth;
                    canvas.height = img.naturalHeight;
                    const ctx = canvas.getContext('2d');
                    if (!ctx) { resolve(null); return; }
                    ctx.drawImage(img, 0, 0);
                    resolve(canvas.toDataURL('image/png'));
                } catch { resolve(null); }
            };
            img.onerror = () => resolve(null);
            img.src = src;
        } catch { resolve(null); }
    });

/** Gold-underlined uppercase section heading. Returns the y where content should start. */
export function sectionLabel(doc: jsPDF, label: string, x: number, y: number): number {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(GOLD_DARK);
    const text = label.toUpperCase();
    doc.text(text, x, y);
    const w = Math.max(doc.getTextWidth(text), 22);
    doc.setDrawColor(GOLD);
    doc.setLineWidth(1.4);
    doc.line(x, y + 4, x + w, y + 4);
    doc.setLineWidth(0.5);
    return y + 17;
}

/** A tinted panel with an accent spine — used for source/destination and supplier/delivery pairs. */
export function partyPanel(
    doc: jsPDF, x: number, y: number, w: number, h: number,
    label: string, accent: string, name: string, sub: string,
): void {
    doc.setDrawColor(BORDER);
    doc.setFillColor(WASH);
    doc.roundedRect(x, y, w, h, 5, 5, 'FD');
    doc.setFillColor(accent);
    doc.roundedRect(x, y, 3.5, h, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(accent);
    doc.text(label, x + 15, y + 18);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text(name, x + 15, y + 34, { maxWidth: w - 26 });

    if (sub) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(MUTED);
        doc.text(sub, x + 15, y + 46, { maxWidth: w - 26 });
    }
}

/** A rounded status pill, right-anchored at x. */
export function drawPill(doc: jsPDF, text: string, x: number, y: number, bg: string, fg: string): void {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    const padX = 9;
    const w = doc.getTextWidth(text) + padX * 2;
    const h = 16;
    const bx = x - w;
    doc.setFillColor(bg);
    doc.roundedRect(bx, y - 11, w, h, 8, 8, 'F');
    doc.setTextColor(fg);
    doc.text(text, bx + padX, y);
}

/**
 * Slim brand strip, logo, right-aligned document title and reference, closed by a hairline rule with
 * a short teal accent. Returns the y directly below the rule.
 */
export function drawDocHeader(
    doc: jsPDF,
    opts: { logo: string | null; title: string; refNo: string; pageW: number; margin: number },
): number {
    const { logo, title, refNo, pageW, margin } = opts;

    doc.setFillColor(TEAL);
    doc.rect(0, 0, pageW, 4, 'F');

    const headerTop = 30;
    if (logo) {
        const h = 34;
        doc.addImage(logo, 'PNG', margin, headerTop, h * LOGO_RATIO, h);
    } else {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.setTextColor(TEAL);
        doc.text('PRIDE BANK LIMITED', margin, headerTop + 22);
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(TEAL);
    doc.text(title, pageW - margin, headerTop + 14, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(MUTED);
    doc.text(`No. ${refNo}`, pageW - margin, headerTop + 30, { align: 'right' });

    const hrY = headerTop + 48;
    doc.setDrawColor(BORDER);
    doc.setLineWidth(0.8);
    doc.line(margin, hrY, pageW - margin, hrY);
    doc.setDrawColor(TEAL);
    doc.setLineWidth(2);
    doc.line(margin, hrY, margin + 54, hrY);
    doc.setLineWidth(0.5);

    return hrY;
}

/** One labelled signature field: a printed value on a solid rule, or a dotted rule to write on. */
export function signatureField(
    doc: jsPDF, x: number, w: number, lineY: number, caption: string, value?: string,
): void {
    if (value) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(INK);
        doc.text(value, x, lineY - 4, { maxWidth: w });
        doc.setDrawColor(BORDER);
        doc.setLineWidth(0.6);
        doc.line(x, lineY, x + w, lineY);
    } else {
        doc.setDrawColor(FAINT);
        doc.setLineWidth(0.6);
        doc.setLineDashPattern([1, 2.2], 0);
        doc.line(x, lineY, x + w, lineY);
        doc.setLineDashPattern([], 0);
    }
    doc.setLineWidth(0.5);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(FAINT);
    doc.text(caption, x, lineY + 9);
}

/** Row of bordered signature cards, each with Name / Signature / Date fields. */
export function drawSignatureCards(
    doc: jsPDF,
    cards: Array<{ role: string; name?: string }>,
    opts: { x: number; y: number; contentW: number; height?: number; gap?: number },
): number {
    const { x, y, contentW } = opts;
    const gap = opts.gap ?? 18;
    const h = opts.height ?? 128;
    const w = (contentW - gap * (cards.length - 1)) / cards.length;

    cards.forEach(({ role, name }, i) => {
        const cx = x + i * (w + gap);
        const padX = 14;
        const fw = w - padX * 2;

        doc.setDrawColor(BORDER);
        doc.roundedRect(cx, y, w, h, 5, 5, 'S');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(TEAL);
        doc.text(role.toUpperCase(), cx + padX, y + 19);

        signatureField(doc, cx + padX, fw, y + 50, 'Name', name || undefined);
        signatureField(doc, cx + padX, fw, y + 82, 'Signature');
        signatureField(doc, cx + padX, fw, y + 114, 'Date');
    });

    return y + h;
}

/**
 * Right-aligns the given columns' header cells to match their right-aligned values.
 *
 * <p>Needed because jspdf-autotable applies {@code columnStyles} to the <b>body section only</b> —
 * head cells fall back to {@code headStyles}, which has no per-column form. Without this, a numeric
 * column's figures sit right while its heading sits left, and the column reads as misaligned.
 *
 * <p>Pass the same index list used for the right-aligned {@code columnStyles} so the two can't drift.
 */
/**
 * Body and heading styles for a printed register.
 *
 * <h2>Why this is shared rather than written twice</h2>
 * The list exporter and the reports exporter carried byte-identical style objects, deliberately, so
 * that a register printed from Reports and the same data printed from its own page came out looking
 * like one document. Two identical literals stay identical only until somebody adjusts one of them —
 * which is exactly what happened the first time these documents were unified, and what this stops
 * happening again.
 *
 * <p>`cellPadding` is the row height. autoTable sizes a row from its content plus this padding, so
 * the vertical figure is the whole of what makes a register feel airy or cramped. It reads 9pt top
 * and bottom rather than the 5 it started at — at 7.5pt type, five points above and below left the
 * lines almost touching their rules, and a register is read by running a finger down a column.
 *
 * <p>The horizontal figure is deliberately left at 5. Widening it would eat the text width every
 * column has to share, and on a register that already runs to eight or ten columns that buys
 * whitespace by causing headings to wrap — which is the opposite of legible.
 */
export const listTableStyles = {
    fontSize: 7.5,
    cellPadding: { top: 9, right: 5, bottom: 9, left: 5 },
    textColor: INK,
    overflow: 'linebreak' as const,
};

/** Heading band for the same tables. Kept beside the body styles so the two cannot drift. */
export const listTableHeadStyles = {
    fillColor: TEAL_50,
    textColor: TEAL_DARK,
    fontStyle: 'bold' as const,
    fontSize: 7,
    // A touch tighter than the body: the heading is one line by design, and matching the body's
    // padding made the band look like an empty first row.
    cellPadding: { top: 7, right: 5, bottom: 7, left: 5 },
};

export const rightAlignHeaders = (columns: number[]) => (data: {
    section: string;
    column: { index: number };
    cell: { styles: { halign: string } };
}): void => {
    if (data.section === 'head' && columns.includes(data.column.index)) {
        data.cell.styles.halign = 'right';
    }
};

/**
 * Writes a wrapped paragraph and returns the y below it.
 *
 * <p>Callers used to advance y by a guessed constant after drawing text, which silently overlapped
 * whatever came next as soon as the copy wrapped to a second line. Measuring the wrap makes the
 * following block's position correct for any length.
 */
export function drawParagraph(
    doc: jsPDF,
    text: string,
    opts: { x: number; y: number; maxWidth: number; fontSize?: number; lineHeight?: number; italic?: boolean; color?: string },
): number {
    const { x, y, maxWidth } = opts;
    const fontSize = opts.fontSize ?? 8.5;
    const lineHeight = opts.lineHeight ?? fontSize * 1.45;

    doc.setFont('helvetica', opts.italic ? 'italic' : 'normal');
    doc.setFontSize(fontSize);
    doc.setTextColor(opts.color ?? MUTED);

    const lines: string[] = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line, i) => doc.text(line, x, y + i * lineHeight));

    return y + (lines.length - 1) * lineHeight;
}

/**
 * Guarantees {@code needed} points of room below {@code y}, starting a new page when there isn't
 * enough. {@code onNewPage} redraws any per-page chrome (e.g. the document header) and returns the y
 * to continue from, so a block that spills over never lands on a bare page or under the footer.
 */
export function ensureSpace(
    doc: jsPDF,
    opts: { y: number; needed: number; pageH: number; margin: number; footerReserve?: number; onNewPage?: () => number },
): number {
    const { y, needed, pageH, margin } = opts;
    const footerReserve = opts.footerReserve ?? 44;

    if (y + needed <= pageH - margin - footerReserve) {
        return y;
    }
    doc.addPage();
    return opts.onNewPage ? opts.onNewPage() : margin + 6;
}

/** Hairline footer with a confidentiality note and page count, stamped on every page. */
export function drawFooter(
    doc: jsPDF,
    opts: { pageW: number; pageH: number; margin: number; note: string; refNo: string },
): void {
    const { pageW, pageH, margin, note, refNo } = opts;
    const pages = doc.getNumberOfPages();
    for (let p = 1; p <= pages; p++) {
        doc.setPage(p);
        const fy = pageH - 26;
        doc.setDrawColor(BORDER);
        doc.setLineWidth(0.5);
        doc.line(margin, fy, pageW - margin, fy);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(FAINT);
        doc.text(`Pride Bank Limited   ·   ${note}   ·   ${refNo}`, margin, fy + 12);
        doc.text(`Page ${p} of ${pages}`, pageW - margin, fy + 12, { align: 'right' });
    }
}
